<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>RSS_Services</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TimeZoneConverter" Version="7.2.0" />
    <ProjectReference Include="..\RSS-DB\RSS-DB.csproj" />
    <PackageReference Include="ZlEmailProvider" Version="1.0.0" />
  </ItemGroup>

</Project>
